image: cypress/browsers:node14.15.0-chrome86-ff82
lhci:
  script:
    - npm install
    - npm install -g @lhci/cli@0.7.x
    - lhci autorun --upload.target=temporary-public-storage --collect.settings.chromeFlags="--no-sandbox" || echo "LHCI failed!"